# Generated by Django 4.2.7 on 2023-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Metal', 'Metal'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Country', 'Country'), ('Hip-Hop', 'Hip-Hop'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Rap', 'Rap'), ('Reggae', 'Reggae'), ('Soundtrack', 'Soundtrack')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
