# Generated by Django 4.2.7 on 2023-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_band_genre_delete_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['genre']},
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Metal', 'Metal'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Country', 'Country'), ('Hip-Hop', 'Hip-Hop'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Rap', 'Rap'), ('Reggae', 'Reggae')], max_length=20),
        ),
    ]
