# Generated by Django 4.2.7 on 2023-11-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_band_options_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
