# Generated by Django 4.2.7 on 2023-11-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_band_image_alter_band_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='image',
        ),
        migrations.AddField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
