# Generated by Django 4.2.7 on 2023-11-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_band_image_band_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='photo',
        ),
    ]
